/**
 * Copyright 2016-present.
 * All rights reserved.
 *
 * This source code is licensed under the  license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 *
 * @author  on 1/16/21.
 *
 * History:
 * @modifier abc@.com on xx/xx/xxxx đã chỉnh sửa abcxyx (Chỉ các thay đổi quan trọng mới cần ghi lại note này)
 */
'use strict';

export const day = [
  {
    'Weak Leg': 0,
    Direct: 0,
    Mega: 0,
    F1: 0,
    Level: 0,
    Bonus: 0,
    'Leadership Bonus': 0,
    total: 0,
    day: '5',
  },
  {
    'Weak Leg': 0,
    Direct: 0,
    Mega: 0,
    F1: 0,
    Level: 0,
    Bonus: 0,
    'Leadership Bonus': 0,
    total: 0,
    day: '4',
  },
  {
    'Weak Leg': 0,
    Direct: 0,
    Mega: 0,
    F1: 0,
    Level: 0,
    Bonus: 0,
    'Leadership Bonus': 0,
    total: 0,
    Order: '92.00',
    day: '3',
  },
  {
    'Weak Leg': 0,
    Direct: 0,
    Mega: 0,
    F1: 0,
    Level: 0,
    Bonus: 0,
    'Leadership Bonus': 0,
    total: 0,
    day: '2',
  },
  {
    'Weak Leg': 0,
    Direct: 0,
    Mega: 0,
    F1: 0,
    Level: 0,
    Bonus: 0,
    'Leadership Bonus': 0,
    total: 0,
    Order: '184.00',
    day: '1',
  },
  {
    'Weak Leg': 0,
    Direct: 0,
    Mega: 0,
    F1: 0,
    Level: 0,
    Bonus: 0,
    'Leadership Bonus': 0,
    total: 0,
    Transfer: '20.00',
    day: '0',
  },
  {
    'Weak Leg': 0,
    Direct: 0,
    Mega: 0,
    F1: 0,
    Level: 0,
    Bonus: 0,
    'Leadership Bonus': 0,
    total: 0,
    day: '6',
  },
];

export const week = [
  {
    'Weak Leg': 0,
    Direct: 0,
    Mega: 0,
    F1: 0,
    Level: 0,
    Bonus: 0,
    'Leadership Bonus': 0,
    total: 0,
    Order: '276.00',
    week: '02',
    year: '2021',
  },
  {
    'Weak Leg': 0,
    Direct: 0,
    Mega: 0,
    F1: 0,
    Level: 0,
    Bonus: 0,
    'Leadership Bonus': 0,
    total: 0,
    Transfer: '160.00',
    week: '01',
    year: '2021',
  },
  {
    'Weak Leg': 0,
    Direct: 0,
    Mega: 0,
    F1: 0,
    Level: 0,
    Bonus: 0,
    'Leadership Bonus': 0,
    total: 0,
    week: '53',
    year: '2020',
  },
  {
    'Weak Leg': 0,
    Direct: 0,
    Mega: 0,
    F1: 0,
    Level: 0,
    Bonus: 0,
    'Leadership Bonus': 0,
    total: 0,
    week: '52',
    year: '2020',
  },
  {
    'Weak Leg': 0,
    Direct: 0,
    Mega: 0,
    F1: 0,
    Level: 0,
    Bonus: 0,
    'Leadership Bonus': 0,
    total: 0,
    week: '51',
    year: '2020',
  },
  {
    'Weak Leg': 0,
    Direct: 0,
    Mega: 0,
    F1: 0,
    Level: 0,
    Bonus: 0,
    'Leadership Bonus': 0,
    total: 0,
    week: '50',
    year: '2020',
  },
  {
    'Weak Leg': 0,
    Direct: 0,
    Mega: 0,
    F1: 0,
    Level: 0,
    Bonus: 0,
    'Leadership Bonus': 0,
    total: 0,
    week: '49',
    year: '2020',
  },
];

export const month = [
  {
    'Weak Leg': 0,
    Direct: 0,
    Mega: 0,
    F1: 0,
    Level: 0,
    Bonus: 0,
    'Leadership Bonus': 0,
    total: 0,
    Order: '276.00',
    Transfer: '160.00',
    month: '01',
    year: '2021',
  },
  {
    'Weak Leg': 0,
    Direct: 0,
    Mega: 0,
    F1: 0,
    Level: 0,
    Bonus: 0,
    'Leadership Bonus': 0,
    total: 0,
    month: '12',
    year: '2020',
  },
  {
    'Weak Leg': 0,
    Direct: 0,
    Mega: 0,
    F1: 0,
    Level: 0,
    Bonus: 0,
    'Leadership Bonus': 0,
    total: 0,
    month: '11',
    year: '2020',
  },
  {
    'Weak Leg': 0,
    Direct: 0,
    Mega: 0,
    F1: 0,
    Level: 0,
    Bonus: 0,
    'Leadership Bonus': 0,
    total: 0,
    month: '10',
    year: '2020',
  },
  {
    'Weak Leg': 0,
    Direct: 0,
    Mega: 0,
    F1: 0,
    Level: 0,
    Bonus: 0,
    'Leadership Bonus': 0,
    total: 0,
    month: '09',
    year: '2020',
  },
  {
    'Weak Leg': 0,
    Direct: 0,
    Mega: 0,
    F1: 0,
    Level: 0,
    Bonus: 0,
    'Leadership Bonus': 0,
    total: 0,
    month: '08',
    year: '2020',
  },
  {
    'Weak Leg': 0,
    Direct: 0,
    Mega: 0,
    F1: 0,
    Level: 0,
    Bonus: 0,
    'Leadership Bonus': 0,
    total: 0,
    month: '07',
    year: '2020',
  },
];
